name: Run GAMS Model

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: gams/gams:latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Inject GAMS license
        env:
          GAMS_LICENSE: ${{ secrets.GAMS_LICENSE }}
        run: |
          echo "$GAMS_LICENSE" > /gams/gamslice.txt

      - name: Run GAMS model
        run: |
          cd epm
          gams main.gms --MODELTYPE RMIP
