name: Run GAMS Model

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: gams/gams:latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Inject GAMS license
      env:
        GAMS_LICENSE: ${{ secrets.GAMS_LICENSE }}
      run: |
        mkdir -p /opt/gams
        echo "$GAMS_LICENSE" > /opt/gams/gamslice.txt

    - name: Run GAMS model
      run: gams epm/main.gms --BASE_FILE epm/base.gms --REPORT_FILE epm/generate_report.gms --READER_FILE epm/input_readers.gms --VERIFICATION_FILE epm/input_verification.gms --TREATMENT_FILE epm/input_treatment.gms --DEMAND_FILE epm/generate_demand.gms